# define keys that can be inherited by members of the workspace
[workspace.package]
authors = ["Photos network developers <info@photos.network>"]
description = "A privacy first **photo storage and sharing service** in the fediverse."
version = "0.6.0"
homepage = "https://photos.network/"
documentation = "https://developers.photos.network/"
repository = "https://github.com/photos-network/core"
readme = "README.md"
license = "AGPL-3.0"
edition = "2021"

[package]
name = "core"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
include = ["src/**/*", "LICENSE.md", "README.md", "CHANGELOG.md"]


[workspace]
members = [
    "crates/core_common",
    "crates/core_photos",
    "crates/core_activity_pub",
    "crates/plugin_interface"
]

# define dependencies to be inherited by members of the workspace
[workspace.dependencies]
core_common = { path = "./crates/core_common" }
# core_oauth = { path = "./crates/core_oauth" }
core_photos = { path = "./crates/core_photos" }
core_activity_pub = { path = "./crates/core_activity_pub" }
activitypub_federation = "~0.4.0"
serde = "~1.0.157"

# core_api = { version = "=0.1.0", path = "./crates/core_api" }
# core_api_crud = { version = "=0.1.0", path = "./crates/api_crud" }
# core_apub = { version = "=0.1.0", path = "./crates/core_activity_pub" }





[dependencies.photos_network_plugin]
version = "0.2.0"
path = "./crates/plugin_interface"


[dependencies]
# core_api = { workspace = true }
core_common = { workspace = true }
core_photos = { workspace = true }
# core_oauth = { workspace = true }
core_activity_pub = { workspace = true }
# core_api_crud = { workspace = true }






abi_stable = "0.11.1"
core_extensions = { version = "1.5.2", default_features = false, features = ["std"] }
serde = "1.0.157"
serde_json = { version = "1.0.79", features = ["raw_value"] }
smallvec = "1.8.0"


anyhow = "1.0.70"
axum = { version = "0.6.2", features = ["ws"] }
oxide-auth = "0.5"
oxide-auth-axum = "0.3.0"

futures = "0.3.25"
futures-channel = "0.3.25"
futures-util = "0.3.25"
rumqttc = "0.21.0"

tokio = { version = "1.24.1", features = ["full"] }
tokio-stream = { version = "0.1.11", features = ["net"] }
tokio-util = { version = "0.7.4", features = ["rt"] }

tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }

tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["registry", "fmt", "std", "json"] }
tracing-appender = "0.2.2"

[dev-dependencies]
pretty_assertions = "1.3.0"
serde_urlencoded = "0.7.1"
reqwest = { version = "0.11", default-features = false, features = ["json", "stream", "multipart"] }
