[package]
name = "media"
description = "Manages all media items in the database and on filesystem."
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
edition.workspace = true

[lib]
name = "media"
path = "src/lib.rs"
doctest = false

[dependencies]
serde = { workspace = true, features = ["derive"] }

# Router
axum = { workspace = true }
tower-http.workspace = true
